spring.application.name=backend

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/campusconnect
spring.datasource.username=root
spring.datasource.password=@gowtham1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=496b6a2249eac8
spring.mail.password=40cb89a5f1798f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server port
server.port=8080

# JWT (you'll use this later for auth)
app.jwt.secret=changeThisToALongRandomSecretStringLater
app.jwt.expirationMs=86400000